
name: A Test Volatilemolotov

on:
  workflow_dispatch:
  pull_request_target:
    paths:
      - 'test'
jobs:
  test_volatilemolotov:
    runs-on: [self-hosted, ubuntu-20.04, main]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/rerun-2-action